version: '3.8'
services:
  dynamodb-local:
    container_name: dynamodb
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb "
    user: "root"
    ports:
      - "8000:8000"
    restart: always