AWSTemplateFormatVersion: 2010-09-09
Description: >-
  url-shortener-backend

Transform:
- AWS::Serverless-2016-10-31

Resources:
  getByLongUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-long-url.getByLongUrlHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get short-url by id, which is the long-url in lowercase.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref URL
      Environment:
        Variables:
          URL_TABLE: !Ref URL
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
  putIShortUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-short-url.putShortUrlHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Store short url in DynamoDB.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref URL
      Environment:
        Variables:
          URL_TABLE: !Ref URL
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST
  deleteShortUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/delete-short-url.deleteShortUrlHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: DELETE short url in DynamoDB.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref URL
      Environment:
        Variables:
          URL_TABLE: !Ref URL
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: DELETE
  proxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/proxy.setCors
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: PROXY set CORS
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref URL
      Environment:
        Variables:
          URL_TABLE: !Ref URL
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: OPTIONS

  URL:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: URL
      AttributeDefinitions:
        - AttributeName: longUrl
          AttributeType: S
      KeySchema:
        - AttributeName: "longUrl"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/api/"