AWSTemplateFormatVersion: 2010-09-09
Description: >-
  url-shortener-backend

Transform:
- AWS::Serverless-2016-10-31

Resources:
  getByLongUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-by-long-url.getByLongUrlHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Get short-url by id, which is the long-url in lowercase.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref URL
      Environment:
        Variables:
          URL_TABLE: !Ref URL
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
  putIShortUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/put-short-url.putShortUrlHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Store short url in DynamoDB.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref URL
      Environment:
        Variables:
          URL_TABLE: !Ref URL
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  URL:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: URL
      AttributeDefinitions:
        - AttributeName: longUrl
          AttributeType: S
        - AttributeName: shortUrl
          AttributeType: S
        - AttributeName: status
          AttributeType: S
        - AttributeName: counter
          AttributeType: N
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: GSI_SHORT_URL
          KeySchema: 
            - AttributeName: shortUrl
              KeyType: HASH
          ProvisionedThroughput:
              ReadCapacityUnits: 3
              WriteCapacityUnits: 1
        

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/api/"
