AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda endpoint for url-shortener

Globals:
  Function:
    Timeout: 3

Resources:
  CreateDynamoDBTable:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        CreateTable:
          Type: Api
          Properties:
            Path: /create
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateTableApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  CreateDynamoDBTable:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt CreateDynamoDBTable.Arn
  CreateDynamoDBTableIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CreateDynamoDBTableRole.Arn